def_i/urls.py
from django.urls import path
from . import views
from . import sitemaps
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

sitemaps = {
'index': sitemaps.IndexSitemap,
}

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('ranking/', views.RankingView.as_view(), name='ranking'),

    # 記事系
    path('article_feed/',views.ArticleFeed.as_view(), name='article_feed'),
    path('article_detail/<int:pk>/',views.ArticleDetail.as_view(),name="article_detail"),
    path('article_post/',views.ArticlePost.as_view(),name='article_post'),
    path('article_post/<int:pk>/',views.ArticlePost.as_view(),name='article_post'),
    path('article_published/<int:pk>/', views.ArticlePublishedView.as_view(), name='article_published'),
    path('article_saved/<int:pk>/', views.ArticleSavedView.as_view(), name='article_saved'),
    path('article_failed/', views.ArticlePostFailed.as_view(), name="article_failed"),
    path('article_edit/<int:pk>/',views.ArticleUpdateView.as_view(),name='article_edit'),
    path('article_delete/<int:pk>/',views.ArticleDeleteView.as_view(),name='article_delete'),
    path('article_talk_delete/<int:pk>/',views.ArticleTalkDeleteView.as_view(),name='article_talk_delete'),

    # 質問系
    path('question_feed/',views.QuestionFeed.as_view(),name='question_feed'),
    path('question_detail/<int:pk>/',views.QuestionDetail.as_view(),name='question_detail'),
    path('question_failed/', views.QuestionPostFailed.as_view(), name="question_failed"),
    path('question_post_suc/<int:pk>/',views.QuestionPostSuc.as_view(),name='question_post_suc'),
    path('question_post/',views.QuestionPost.as_view(),name='question_post'),
    path('question_edit/<int:pk>/',views.QuestionUpdateView.as_view(),name='question_edit'),
    path('question_delete/<int:pk>/',views.QuestionDeleteView.as_view(),name='question_delete'),
    path('question_talk_delete/<int:pk>/',views.QuestionTalkDeleteView.as_view(),name='question_talk_delete'),

    # コース系
    path('course/', views.course, name="course"),
    path('course/<str:category>/',views.CourseList.as_view(),name='course_list'),
    path('mark_as_studying/', views.mark_as_studying, name="mark_as_studying"),
    path('task_detail/<str:category>/<int:course_num>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('task_detail/<str:category>/<int:course_num>/<int:lesson_num>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('task_detail/<int:pk>/question/post', views.TaskQuestionPost.as_view(), name='task_question_post'),
    path('task_detail/<int:pk>/article/post', views.TaskArticlePost.as_view(), name='task_article_post'),
    path('task_detail/<int:pk>/article_for_complete/post', views.TaskCompleteArticlePost.as_view(), name="task_complete_article"),
    path('task_detail/<int:pk>/article_for_complete_edit/', views.TaskCompleteArticleUpdate.as_view(), name="task_complete_article_edit"),
    path('complete/<int:pk>/', views.lesson_complete, name="complete"),

    # マイページ系
    path('message_notification/',views.MessageNotification.as_view(),name='message_notification'),
    path('like/<int:pk>/',views.LikeView,name='like'),
    path('bookmark/<int:pk>/', views.BookMarkView, name='bookmark'),
    path('user_page/<int:pk>/',views.userpage_view,name='user_page'),
    path('my_page/',views.mypage_view,name="my_page"),

    # LINE関連
    path('callback/', views.callback, name='callback'),

    #robots
    path('robots.txt',TemplateView.as_view(template_name='def_i/robots.txt', content_type='text/plain')),

    #sitemaps
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    #notify
    path('notify_bell', views.notify, name="notify_bell"),

]

def_init/urls.py
from django.contrib import admin
from django.urls import path,include
import def_i.views as def_i #いる？
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('def_i.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('markdownx/',include('markdownx.urls')),
    # path('cms/',include('cms_integration.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

def_i/models.py
import requests

from django.contrib.auth import get_user_model
from django.core.validators import validate_image_file_extension
from django.db import models
from django.db.models import Q
from django.shortcuts import resolve_url
from django.utils import timezone
from linebot import LineBotApi
from linebot.models import TextSendMessage
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from taggit.managers import TaggableManager
from stdimage.models import StdImageField

from def_init.secret_settings import *

domain = "https://def-init.demia.co.jp"
User = get_user_model()


class Category(models.Model):
    title = models.CharField(max_length=10)
    category_image = models.FileField(upload_to='def_i/img')
    description = models.TextField(max_length=100, null=True)

    def __str__(self):
        return str(self.title)


class Course(models.Model):
    title = models.CharField(max_length=30)
    course_num = models.PositiveSmallIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"({self.category}-{self.course_num}){self.title}"


class Lesson(models.Model):
    title = models.CharField(max_length=30)
    contents = MarkdownxField(max_length=100000, null=True)
    lesson_num = models.PositiveSmallIntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.PROTECT, related_name="lessons")

    def __str__(self):
        return f"({self.course.category}-{self.course.course_num}-{self.lesson_num}){self.title}"

    def formatted_markdown(self):
        return markdownify(self.contents)


class ClearedLesson(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "cleared_user")
    lesson = models.ForeignKey(Lesson, on_delete=models.SET_NULL, related_name = "cleared_lesson", null=True)
    cleared_at = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return f"{self.lesson.course.category}-{self.lesson.course.course_num}-{self.lesson.lesson_num}"


class StudyingCategory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_category")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="studying_category")

    def __str__(self):
        return f"{self.user} now studying {self.category}"


class Article(models.Model):
    poster = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="user_article",null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, related_name="category_article", null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, related_name="course_article", null=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.SET_NULL, related_name="lesson_article", null=True)
    title = models.CharField(max_length=50)
    content = MarkdownxField(max_length=100000)
    like_count = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(default=timezone.now)
    tags = TaggableManager(blank=True)
    is_published = models.BooleanField(default=False)
    for_lesson_complete = models.BooleanField(default=False)
    # 画像を添付する
    # works just like django's ImageField
    article_image_1 = StdImageField(
        upload_to='def_i/img',
        null=True,
        blank=True,
        variations={'thumbnail': {'width': 300, 'height': 225, "crop": True}},
        validators=[validate_image_file_extension]
    )
    article_image_2 = StdImageField(
        upload_to="def_i/img",
        null=True,
        blank=True,
        variations={'thumbnail': {'width': 300, 'height': 225, "crop": True}},
        validators=[validate_image_file_extension]
    )

    def __str__(self):
        return f"{self.title}({self.poster})"

    def formatted_markdown(self):
        return markdownify(self.content)


class Question(models.Model):
    poster = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="user_question", null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, related_name="category_question", null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, related_name="course_question", null=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.SET_NULL, related_name="lesson_question", null=True)
    title = models.CharField(max_length=50)
    content = MarkdownxField(max_length=100000)
    is_answered = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    tags = TaggableManager(blank=True)
    # 画像を添付する
    question_image_1 = StdImageField(
        upload_to='def_i/img',
        null=True,
        blank=True,
        variations={'thumbnail': {'width': 300, 'height': 225, "crop": True}},
        validators=[validate_image_file_extension]
    )
    question_image_2 = StdImageField(
        upload_to="def_i/img",
        null=True,
        blank=True,
        variations={'thumbnail': {'width': 300, 'height': 225, "crop": True}},
        validators=[validate_image_file_extension]
    )

    bookmark_count = models.PositiveIntegerField(default=0)
    # ブラウザのプッシュ通知
    def browser_push(self):
        pass

    def notify_new_question(self):
        line_bot_api = LineBotApi(
            channel_access_token=LINE_CHANNEL_ACCESS_TOKEN)
        notify_to = LineFriend.objects.filter(is_answerer=True)
        for push in notify_to:
            line_bot_api.push_message(push.line_user_id, TextSendMessage(
                text=f"【{self.category}】 の質問 【{self.title}】 が投稿されました。回答をお願いします。{domain}{resolve_url('question_detail', self.pk)}"))

    def formatted_markdown(self):
        return markdownify(self.content)

    def __str__(self):
        return f"{self.title}({self.poster})"


class Like(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_like")
    has_noticed = models.BooleanField(default=False)


class BookMark(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    has_noticed = models.BooleanField(default=False)


class Talk(models.Model):
    msg = MarkdownxField(max_length=5000)
    msg_from = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="msg_from",null=True)
    msg_to = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="msg_to",null=True)
    time = models.DateTimeField(auto_now_add=True)
    has_noticed = models.BooleanField(default=False)

    def formatted_markdown(self):
        return markdownify(self.msg)


CATEGORY_CHOICE = (
    ('記事', '記事'),
    ('質問', '質問'),
)


class TalkAtArticle(Talk):
    msg_at = models.ForeignKey(Article, on_delete=models.CASCADE)
    category = models.CharField(max_length=10,
                                choices=CATEGORY_CHOICE, default='記事')

    def notify_new_comment(self):
        line_bot_api = LineBotApi(
            channel_access_token=LINE_CHANNEL_ACCESS_TOKEN)
        other_commenters = TalkAtArticle.objects.filter(
            msg_at=self.msg_at).values("msg_from")  # 同じ記事にコメントした人全員に通知
        notify_to = LineFriend.objects.filter(Q(user=self.msg_to) | Q(
            user__in=other_commenters)).exclude(user=self.msg_from)
        print("to:", notify_to)
        for push in notify_to:
            if push.notify_comment:
                if push.user == self.msg_at.poster:
                    line_bot_api.push_message(
                        push.line_user_id,
                        TextSendMessage(
                            text=f"あなたの 【{self.msg_at.category}】 のノート 【{self.msg_at}】 にコメントが来ました。{domain}{resolve_url('article_detail', self.msg_at.pk)}")
                    )
                else:
                    line_bot_api.push_message(
                        push.line_user_id,
                        TextSendMessage(
                            text=f"あなたがコメントした 【{self.msg_at.category}】 のノート 【{self.msg_at}】 にコメントが来ました。{domain}{resolve_url('article_detail', self.msg_at.pk)}")
                    )


class TalkAtQuestion(Talk):
    msg_at = models.ForeignKey(Question, on_delete=models.CASCADE)
    category = models.CharField(max_length=10,
                                choices=CATEGORY_CHOICE, default='質問')

    def notify_new_comment(self):
        line_bot_api = LineBotApi(
            channel_access_token=LINE_CHANNEL_ACCESS_TOKEN)
        other_commenters = TalkAtQuestion.objects.filter(
            msg_at=self.msg_at).values("msg_from")  # 同じ質問にコメントした人全員に通知？
        notify_to = LineFriend.objects.filter(Q(user=self.msg_to) | Q(
            user__in=other_commenters)).exclude(user=self.msg_from)  # 投稿者か，その質問でコメントしてる人,かつ今コメントした人以外
        for push in notify_to:
            if push.notify_answer:
                if push.user == self.msg_at.poster:
                    line_bot_api.push_message(
                        push.line_user_id,
                        TextSendMessage(
                            text=f"あなたの 【{self.msg_at.category}】 の質問 【{self.msg_at}】 にコメントが来ました。{domain}{resolve_url('question_detail', self.msg_at.pk)}")
                    )
                else:
                    line_bot_api.push_message(
                        push.line_user_id,
                        TextSendMessage(
                            text=f"あなたが回答した 【{self.msg_at.category}】 の質問 【{self.msg_at}】 にコメントが来ました。{domain}{resolve_url('question_detail', self.msg_at.pk)}")
                    )

    def __str__(self):
        return f"FROM {self.msg_from} TO {self.msg_to} AT {self.msg_at}"


class LineFriend(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)  # unique=True?
    line_user_id = models.CharField(max_length=100)
    is_intern = models.BooleanField(default=False)
    is_answerer = models.BooleanField(default=False)

def_i/templates/def_i/article_detail.html
{% extends 'def_i/base.html' %}
{% load static sass_tags %}
{% block extra_style %}
<link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
<link rel="stylesheet" href="{% sass_src 'def_i/css/popup.scss' %}">
<link rel="stylesheet" href="{% sass_src 'def_i/css/article.scss' %}">
<link rel="stylesheet" href="{% sass_src 'def_i/css/detail_base.scss' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock extra_style %}

{% block menubar %}{% endblock menubar %}

{% block contents %}
<div class="main-bar">

    <div id="note" class="contents">
        <h1 class="contents-title">{{contents.title}}</h1>
        <div class="contents-info">
            <div class="like-outer">
                {% include 'def_i/like.html' %}
            </div>
            <a href="{% url 'task_detail' contents.category contents.course.course_num contents.lesson.lesson_num %}">
                <div class="contents-info-at">
                    <div class="contents-info-at-category">{{contents.category}}</div>
                    <div>レッスン{{contents.course.course_num}}-{{contents.lesson.lesson_num}}</div>
                </div>
            </a>
            <div>{{contents.created_at|date:"Y/n/j H:i"}}</div>
        </div>

        <div class="contents-text">
            {{contents.formatted_markdown|safe}}
        </div>
        <div class="contents-images">
            {% if contents.article_image_1 %}
            <label>
                <img src="{{contents.article_image_1.thumbnail.url}}" alt="">
                <input type="checkbox" id="show_popup_1">
                <div id="popup_1">
                    <img src="{{contents.article_image_1.url}}" alt="">
                    {% if contents.article_image_2 %}
                    <input type="image" src="{% static 'def_i/img/next_icon.svg' %}" id="to_next_img_1">
                    {% endif %}
                </div>
            </label>
            {% endif %}
            {% if contents.article_image_2 %}
            <label>
                <img src="{{contents.article_image_2.thumbnail.url}}" alt="">
                <input type="checkbox" id="show_popup_2">
                <div id="popup_2">
                    {% if contents.article_image_1 %}
                    <input type="image" src="{% static 'def_i/img/back_icon_white.svg' %}" id="to_prev_img_2">
                    {% endif %}
                    <img src="{{contents.article_image_2.url}}" alt="">
                </div>
            </label>
            {% endif %}
        </div>

        {% if user == contents.poster %}
        <div class="contents-buttons">
            <span class="btn-edit"><a href="{% url 'article_edit' contents.pk %}">編集する</a></span>
            <span class="btn-delete"><a href="{% url 'article_delete' contents.pk %}">削除する</a></span>
        </div>

        {% endif %}
    </div>

    <div class="comments-wrapper">
        <h2 class="comments-wrapper__title" id="comments">コメント</h2>

        {% for c in comments %}
            <article class="comment">
                <div class="comment-info">
                    {% if c.msg_from %}
                    <a href="{% url 'user_page' c.msg_from.pk %}">
                        {% if c.msg_from.user_image %}
                            <img src="{{c.msg_from.user_image.url}}" width="30" alt="">
                        {% else %}
                            <img src="{% static 'def_i/img/default.png' %}" alt="">
                        {% endif %}
                        <p>{{c.msg_from}}</p>
                    </a>
                    {% endif %}
                    <p>{{c.time|date:"Y/n/j H:i"}}</p>
                </div>
                <div class="comment-text">{{c.formatted_markdown|safe}}</div>
                {% if c.msg_from == user %}<p class="delete_comment"><a href="{% url 'article_talk_delete' c.pk %}">削除</a></p>{% endif %}
            </article>
            {% empty %}
            <p class="no-contents">コメントがありません．</p>
            {% endfor %}
    </div>

    <div class="form-wrapper">
        <form method="POST">
            {% csrf_token %}
            {{comment_form.msg}}
            <button type='submit' name="comment_form">
                <img src="{% static 'def_i/img/send-icon.svg' %}" alt="コメントを送信">
            </button>
        </form>
    </div>
</div>

<!-- サイドバー -->
<div class="sidebar">
    <div class="sidebar-poster">
        <h3>投稿者</h3>
        {% if contents.poster %}
        <a href="{% url 'user_page' contents.poster.pk %}">
            <div class="sidebar-poster-info">
                {% if contents.poster.user_image %}
                    <img src="{{contents.poster.user_image.url}}" alt="">
                {% else %}
                    <img src="{% static 'def_i/img/default.png' %}" alt="">
                {% endif %}
                {{contents.poster}}
            </div>
        </a>
        {% endif %}
        {% if user == contents.poster %}
            <form name="publish_form" method="POST">
                {% csrf_token %}
                <input type="hidden" name="publish_form">
                {% if contents.is_published %}
                    <input type="checkbox" id="id_is_published" name="publish" checked>
                {% else %}
                    <input type="checkbox" id="id_is_published" name="publish">
                {% endif %}
                <span>ノートを公開する</span>
            </form>
        {% endif %}
    </div>
    <div class="sidebar-move">
        <div id="to_note">ノート</div>
        <div id="to_comment">コメント</div>
    </div>

    <h3>関連したノート</h3>
    <div class="related-contents">
        {% for article in related_articles %}
        <div class="related-contents-title">
            <a href="{% url 'article_detail' article.pk %}">{{article.title|truncatechars:40}}</a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock contents %}
{% block javascript %}
<script>
    //jQueryあんまりよくないと知る前に作ったので使っています．．．
    $(document).ready(function(e){
        $(document).on('click','#like',function(e){
            e.preventDefault(); //button&POSTに対しては効きません．．．．
            $.ajax({
                type:'GET',
                url:"{% url 'like' contents.pk %}",
                success:function(response){
                    heartMark = document.getElementById('like')
                    if(response.liked){
                        $(heartMark).html("<img src=" + "{% static 'def_i/img/good-after.svg' %}" +  " alt=" + "いいねを解除" + " width=" + "22" + ">")
                    }
                    else{
                        $(heartMark).html("<img src=" + "{% static 'def_i/img/good-before.svg' %}" + " alt=" + "いいねを解除" + " width=" + "22" + ">")
                    }
                    likeCount = document.getElementById('count')
                    $(likeCount).text(response.count)
                }
            })
        })
    })
const toNote = document.getElementById("to_note");
const toComments = document.getElementById("to_comment");

// ノート本体へスクロール
document.getElementById("to_note").addEventListener('click', function(){
    const note = document.getElementById("note");
    const note_position = note.getBoundingClientRect();
    //classList.addとremoveでやると丁寧
    toComments.style.backgroundColor = '#fbfcfe'
    toNote.style.backgroundColor = "#f5f5f5"
    window.scrollTo(0, note_position.top);
});

// コメントへスクロール
document.getElementById("to_comment").addEventListener('click', function(){
    const comments = document.getElementById("comments");
    const comments_position = comments.getBoundingClientRect();
    toNote.style.backgroundColor = '#fbfcfe';
    toComments.style.backgroundColor = '#f5f5f5'
    window.scrollTo(0, comments_position.top);
});

// ノート公開
document.getElementById("id_is_published").addEventListener('change', function(){
    document.publish_form.submit();
});

const showFirstPopup = document.getElementById("show_popup_1");
const showSecondPopup = document.getElementById("show_popup_2");
document.getElementById("to_next_img_1").addEventListener('click', function(){
    showFirstPopup.checked = false;
    showSecondPopup.checked = true;
});
document.getElementById("to_prev_img_2").addEventListener('click', function(){
    showFirstPopup.checked = true;
    showSecondPopup.checked = false;
});

</script>
{% endblock javascript %}

def_i/templates/def_i/article_edit.html
{% extends 'def_i/base.html' %}
{% load static sass_tags %}
{% block extra_style %}
<link rel="stylesheet" href="{% sass_src 'def_i/css/popup.scss' %}">
<link rel="stylesheet" href="{% sass_src 'def_i/css/article.scss' %}">
<link rel="stylesheet" href="{% sass_src 'def_i/css/article_post.scss' %}">
<link rel="stylesheet" href="{% sass_src 'def_i/css/edit_base.scss' %}">
{% endblock extra_style %}
{% block menubar %}{% endblock menubar %}
{% block contents %}

<form action="" method="POST" class="postform-form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="postnow">
        <label class="post_checkbox" for="id_is_published">
            <input type="checkbox" name="is_published" id="id_is_published">
            <span class="checkbox_is_published"></span>
            <span>ノートを公開する</span>
        </label>
        {% block extra_checkbox %}{% endblock %}
    </div>
    <div>{{form.title}}</div>
    <div class="note-at">
        {{form.category}}
        {{form.course}}
        {{form.lesson}}
    </div>

    <div class="content">
        {{form.content}}
        <label id="label_image_1" {% if form.article_image_1.value %}class="hidden_class"{% endif %}>
            <div {% if form.article_image_1.value or form.article_image_2.value %}class="article_image_icon icon_with_preview"{% else %}class="article_image_icon" {% endif %}>
                <img src="{% static 'def_i/img/img-icon.svg' %}" alt="">
            </div>
            <input type="file" name="article_image_1" id="id_article_image_1" accept="image/*">
            <input type="checkbox" name="article_image_1-clear" id="article_image_1-clear_id" class="hidden_class">
        </label>
        <label id="label_image_2" {% if form.article_image_2.value %}class="hidden_class"{% endif %}>
            <div {% if form.article_image_1.value or form.article_image_2.value %}class="article_image_icon icon_with_preview" {% else %}class="article_image_icon" {% endif %}>
                <img src="{% static 'def_i/img/img-icon.svg' %}" alt="">
            </div>
            <input type="file" name="article_image_2" id="id_article_image_2" accept="image/*">
            <input type="checkbox" name="article_image_2-clear" id="article_image_2-clear_id" class="hidden_class">
        </label>
        <div id="preview" {% if form.article_image_1.value or form.article_image_2.value %}class="preview preview_space"{% else %}class="preview" {% endif %}>
            {% if form.article_image_1.value %}
            <div id="new_img_wrapper_1">
                <button type="button" class="img_delete_btn" id="delete_image_1">削除する</button>
                <label>
                    <img src="{{object.article_image_1.url}}" alt="">
                    <input type="checkbox" id="show_popup_1">
                    <div id="popup_1">
                        <input type="image" src="{% static 'def_i/img/next_icon.svg' %}" id="to_next_img_1">
                        <img src="{{object.article_image_1.url}}" alt="">
                    </div>
                </label>
            </div>
            {% else %}
            <div id="new_img_wrapper_1"></div>
            {% endif %}
            {% if form.article_image_2.value %}
            <div id="new_img_wrapper_2">
                <button type="button" class="img_delete_btn" id="delete_image_2">削除する</button>
                <label>
                    <img src="{{object.article_image_2.url}}" alt="">
                    <input type="checkbox" id="show_popup_2">
                    <div id="popup_2">
                        <input type="image" src="{% static 'def_i/img/back_icon_white.svg' %}" id="to_prev_img_2">
                        <img src="{{object.article_image_2.url}}" alt="">
                    </div>
                </label>
            </div>
            {% else %}
            <div id="new_img_wrapper_2"></div>
            {% endif %}
        </div>
    </div>
    <button type="submit" class="postform-btn">ノートを投稿する</button>
</form>
{% endblock contents %}

{% block javascript %}
<script>
    const courses = JSON.parse('{{course_dict|escapejs}}');
    const lessons = JSON.parse('{{lesson_dict|escapejs}}');
    const toNextIconSource = "{% static 'def_i/img/next_icon.svg' %}";
    const toPrevIconSource = "{% static 'def_i/img/back_icon_white.svg' %}";

    const newImgWrapper1 = document.getElementById("new_img_wrapper_1");
    const newImgWrapper2 = document.getElementById("new_img_wrapper_2");

    if (newImgWrapper1.hasChildNodes() || newImgWrapper2.hasChildNodes()){
        document.getElementById("id_content").classList.add("add_preview_space");
    }
</script>
<script src="{% static 'def_i/js/filter.js' %}"></script>
<script src="{% static 'def_i/js/upload_img.js' %}"></script>
{% endblock javascript %}

def_i/templates/def_i/like.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head></head>
<body>
    <form action="{% url 'like' contents.pk %}" method="POST">
    {% csrf_token %}
    {% if contents.id in liked_set %}
        <span id="like" name="{{contents.id}}">
            <img src="{% static 'def_i/img/good-after.svg' %}" alt="いいねを解除" width="22">
        </span>
    {% else %}
        <span id="like" name="{{contents.id}}">
            <img src="{% static 'def_i/img/good-before.svg' %}" alt="いいね" width="22">
        </span>
    {% endif %}
    </form>
    <p name="{{contents.id}}" class="count" id="count"> {{ contents.like_set.count }} </p>
</body>
</html>

def_i/templates/def_i/task_article_edit.html
{% extends 'def_i/article_edit.html' %}

{% block extra_checkbox %}
<label class="post_checkbox" for="id_clear">
    <input type="checkbox" name="id_clear" id="id_clear">
    <span class="checkbox_is_published"></span>
    <span>課題をクリアする</span>
</label>
<span class="caution">{{ caution }}</span>
{% endblock extra_checkbox %}